spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: Opsueaxqx1578!
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto:  validate
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
  thymeleaf:
    cache: false
